export const ENV = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  FRONTEND_URL: 'FRONTEND_URL',
  SWAGGER_ENABLED: 'SWAGGER_ENABLED',
  COOKIE_SECURE: 'COOKIE_SECURE',
  HEALTH_READINESS_KEY: 'HEALTH_READINESS_KEY',
  JWT_SECRET: 'JWT_SECRET',
  RABBITMQ_URL: 'RABBITMQ_URL',
} as const;

export const ENV_DEFAULTS = {
  PORT: 4006,
  FRONTEND_URL: 'http://localhost',
  SWAGGER_ENABLED: false,
  COOKIE_SECURE: undefined,
} as const;
