apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: campuscore-tls
spec:
  secretName: replace-with-real-staging-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: replace-with-real-staging-cluster-issuer
  dnsNames:
    - replace-with-real-staging-host.example.com

