apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: campuscore-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: replace-with-prod-cluster-secret-store
  target:
    name: campuscore-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: POSTGRES_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: JWT_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: JWT_REFRESH_SECRET
    - secretKey: HEALTH_READINESS_KEY
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: HEALTH_READINESS_KEY
    - secretKey: INTERNAL_SERVICE_TOKEN
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: INTERNAL_SERVICE_TOKEN
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: RABBITMQ_PASSWORD
    - secretKey: MINIO_USER
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: MINIO_USER
    - secretKey: MINIO_PASSWORD
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: MINIO_PASSWORD
    - secretKey: SMTP_USER
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: replace-with-prod/campuscore/runtime
        property: SMTP_PASSWORD
