apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campuscore
spec:
  tls:
    - hosts:
        - campuscore.example.com
      secretName: campuscore-prod-tls
  rules:
    - host: campuscore.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: campuscore-nginx
                port:
                  number: 80
