apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campuscore-prod

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: campuscore-shared-env
  - path: patch-secrets.yaml
    target:
      kind: Secret
      name: campuscore-secrets
  - path: patch-nginx-service.yaml
    target:
      kind: Service
      name: campuscore-nginx
