apiVersion: v1
kind: Secret
metadata:
  name: campuscore-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: campuscore-local-postgres-password
  JWT_SECRET: campuscore-local-jwt-secret-12345
  JWT_REFRESH_SECRET: campuscore-local-refresh-secret-12345
  HEALTH_READINESS_KEY: campuscore-local-readiness-key-12345
  INTERNAL_SERVICE_TOKEN: campuscore-local-internal-service-token-12345
  RABBITMQ_PASSWORD: campuscore-local-rabbitmq-password
  MINIO_USER: campuscore
  MINIO_PASSWORD: campuscore-local-minio-password
  SMTP_USER: local-smtp-user
  SMTP_PASSWORD: local-smtp-password
