apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: campuscore-tls
spec:
  secretName: campuscore-staging-tls
  issuerRef:
    kind: ClusterIssuer
    name: replace-with-staging-cluster-issuer
  dnsNames:
    - staging.campuscore.example.com
