apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campuscore-staging

resources:
  - ../staging-generic
  - certificate.yaml
  - external-secret.yaml

patches:
  - path: delete-placeholder-secret.yaml
    target:
      kind: Secret
      name: campuscore-secrets
