apiVersion: v1
kind: Secret
metadata:
  name: campuscore-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: replace-me-with-staging-postgres-password
  JWT_SECRET: replace-me-with-staging-jwt-secret
  JWT_REFRESH_SECRET: replace-me-with-staging-refresh-secret
  HEALTH_READINESS_KEY: replace-me-with-staging-readiness-key
  INTERNAL_SERVICE_TOKEN: replace-me-with-staging-internal-service-token
  RABBITMQ_PASSWORD: replace-me-with-staging-rabbitmq-password
  MINIO_USER: replace-me-with-staging-minio-user
  MINIO_PASSWORD: replace-me-with-staging-minio-password
  SMTP_USER: replace-me-with-staging-smtp-user
  SMTP_PASSWORD: replace-me-with-staging-smtp-password
