export {
  ACCESS_TOKEN_COOKIE,
  REFRESH_TOKEN_COOKIE,
  CSRF_COOKIE,
  CSRF_HEADER,
  CSRF_HEADER_NAME,
  parseCookieHeader,
  normalizeSetCookie,
  extractCookieValue,
  toCookieHeader,
  extractAccessTokenFromCookieHeader,
  extractAccessTokenFromRequest,
  extractRefreshTokenFromRequest,
  hasBearerAuthorization,
  hasSessionCookie,
} from '@campuscore/platform-auth';
