apiVersion: v1
kind: ConfigMap
metadata:
  name: campuscore-shared-env
data:
  NODE_ENV: production
  SWAGGER_ENABLED: "false"
  COOKIE_SECURE: "true"
  JWT_EXPIRATION: 15m
  JWT_REFRESH_EXPIRATION: 7d
  FRONTEND_URL: https://campuscore.example.com
  POSTGRES_DB: campuscore
  POSTGRES_USER: campuscore
  RABBITMQ_USER: campuscore
  MINIO_BUCKET: campuscore
  MINIO_PORT: "9000"
  EMAIL_FROM: noreply@campuscore.edu
  EMAIL_FROM_NAME: CampusCore Administration
  SMTP_HOST: smtp.example.com
  SMTP_PORT: "587"
  SMTP_SECURE: "true"
