apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance-service
          image: campuscore-finance-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
              name: http
          envFrom:
            - configMapRef:
                name: campuscore-shared-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: RABBITMQ_PASSWORD
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: SMTP_PASSWORD
            - name: DATABASE_URL
              value: postgresql://campuscore:$(POSTGRES_PASSWORD)@postgres:5432/campuscore?schema=finance
            - name: RABBITMQ_URL
              value: amqp://campuscore:$(RABBITMQ_PASSWORD)@rabbitmq:5672
            - name: CORE_API_INTERNAL_URL
              value: http://core-api:4000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: JWT_SECRET
            - name: HEALTH_READINESS_KEY
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: HEALTH_READINESS_KEY
            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: campuscore-secrets
                  key: INTERNAL_SERVICE_TOKEN
            - name: PORT
              value: "4002"
          readinessProbe:
            exec:
              command:
                - sh
                - -lc
                - wget --no-verbose --tries=1 --header="X-Health-Key: $HEALTH_READINESS_KEY" -O- http://127.0.0.1:4002/api/v1/health/readiness >/dev/null
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: 4002
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
